[project]
name = "ia-pet-inicial"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "document>=1.0",
    "docx>=0.2.4",
    "dotenv>=0.9.9",
    "openai>=2.7.2",
    "pyside6>=6.10.0",
    "python-docx>=1.2.0",
]
